version: "3.9"

services:
  bank_api_gatway:
    container_name: bank_api_gatway
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - IS_DOCKER=true

networks:
  default:
    external:
      name: bank_api_network