// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.19.4
// source: pkg/common/proto/bank-funds-query.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_common_proto_bank_funds_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_bank_funds_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_bank_funds_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  []string `protobuf:"bytes,2,rep,name=error,proto3" json:"error,omitempty"`
	Data   int32    `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_common_proto_bank_funds_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_bank_funds_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_bank_funds_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetBalanceResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetBalanceResponse) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_pkg_common_proto_bank_funds_query_proto protoreflect.FileDescriptor

var file_pkg_common_proto_bank_funds_query_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2d, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x2d, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x62, 0x61, 0x6e, 0x6b, 0x5f,
	0x66, 0x75, 0x6e, 0x64, 0x73, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x23, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x56, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x72, 0x0a, 0x15, 0x42, 0x61, 0x6e, 0x6b,
	0x46, 0x75, 0x6e, 0x64, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x59, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x23, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x66, 0x75, 0x6e, 0x64,
	0x73, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02,
	0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_common_proto_bank_funds_query_proto_rawDescOnce sync.Once
	file_pkg_common_proto_bank_funds_query_proto_rawDescData = file_pkg_common_proto_bank_funds_query_proto_rawDesc
)

func file_pkg_common_proto_bank_funds_query_proto_rawDescGZIP() []byte {
	file_pkg_common_proto_bank_funds_query_proto_rawDescOnce.Do(func() {
		file_pkg_common_proto_bank_funds_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_common_proto_bank_funds_query_proto_rawDescData)
	})
	return file_pkg_common_proto_bank_funds_query_proto_rawDescData
}

var file_pkg_common_proto_bank_funds_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_common_proto_bank_funds_query_proto_goTypes = []interface{}{
	(*GetBalanceRequest)(nil),  // 0: bank_funds_query.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 1: bank_funds_query.GetBalanceResponse
}
var file_pkg_common_proto_bank_funds_query_proto_depIdxs = []int32{
	0, // 0: bank_funds_query.BankFundsQueryService.GetBalance:input_type -> bank_funds_query.GetBalanceRequest
	1, // 1: bank_funds_query.BankFundsQueryService.GetBalance:output_type -> bank_funds_query.GetBalanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_common_proto_bank_funds_query_proto_init() }
func file_pkg_common_proto_bank_funds_query_proto_init() {
	if File_pkg_common_proto_bank_funds_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_common_proto_bank_funds_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_common_proto_bank_funds_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_common_proto_bank_funds_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_common_proto_bank_funds_query_proto_goTypes,
		DependencyIndexes: file_pkg_common_proto_bank_funds_query_proto_depIdxs,
		MessageInfos:      file_pkg_common_proto_bank_funds_query_proto_msgTypes,
	}.Build()
	File_pkg_common_proto_bank_funds_query_proto = out.File
	file_pkg_common_proto_bank_funds_query_proto_rawDesc = nil
	file_pkg_common_proto_bank_funds_query_proto_goTypes = nil
	file_pkg_common_proto_bank_funds_query_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BankFundsQueryServiceClient is the client API for BankFundsQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BankFundsQueryServiceClient interface {
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
}

type bankFundsQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankFundsQueryServiceClient(cc grpc.ClientConnInterface) BankFundsQueryServiceClient {
	return &bankFundsQueryServiceClient{cc}
}

func (c *bankFundsQueryServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/bank_funds_query.BankFundsQueryService/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankFundsQueryServiceServer is the server API for BankFundsQueryService service.
type BankFundsQueryServiceServer interface {
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
}

// UnimplementedBankFundsQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBankFundsQueryServiceServer struct {
}

func (*UnimplementedBankFundsQueryServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}

func RegisterBankFundsQueryServiceServer(s *grpc.Server, srv BankFundsQueryServiceServer) {
	s.RegisterService(&_BankFundsQueryService_serviceDesc, srv)
}

func _BankFundsQueryService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankFundsQueryServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank_funds_query.BankFundsQueryService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankFundsQueryServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BankFundsQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bank_funds_query.BankFundsQueryService",
	HandlerType: (*BankFundsQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _BankFundsQueryService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/common/proto/bank-funds-query.proto",
}
