// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.19.4
// source: pkg/common/proto/bank-account-query.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Holder   string `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	IsActive bool   `protobuf:"varint,3,opt,name=isActive,proto3" json:"isActive,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_bank_account_query_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *Account) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type FindAllAccountsResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accounts []*Account `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Total    int32      `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Count    int32      `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Page     int32      `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *FindAllAccountsResponseData) Reset() {
	*x = FindAllAccountsResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAccountsResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAccountsResponseData) ProtoMessage() {}

func (x *FindAllAccountsResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAccountsResponseData.ProtoReflect.Descriptor instead.
func (*FindAllAccountsResponseData) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_bank_account_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllAccountsResponseData) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *FindAllAccountsResponseData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FindAllAccountsResponseData) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FindAllAccountsResponseData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FindAllAccountsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *FindAllAccountsRequest) Reset() {
	*x = FindAllAccountsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAccountsRequest) ProtoMessage() {}

func (x *FindAllAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAccountsRequest.ProtoReflect.Descriptor instead.
func (*FindAllAccountsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_bank_account_query_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllAccountsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FindAllAccountsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32                        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  []string                     `protobuf:"bytes,2,rep,name=error,proto3" json:"error,omitempty"`
	Data   *FindAllAccountsResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FindAllAccountsResponse) Reset() {
	*x = FindAllAccountsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAccountsResponse) ProtoMessage() {}

func (x *FindAllAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAccountsResponse.ProtoReflect.Descriptor instead.
func (*FindAllAccountsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_bank_account_query_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllAccountsResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FindAllAccountsResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *FindAllAccountsResponse) GetData() *FindAllAccountsResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FindAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindAccountRequest) Reset() {
	*x = FindAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccountRequest) ProtoMessage() {}

func (x *FindAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccountRequest.ProtoReflect.Descriptor instead.
func (*FindAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_bank_account_query_proto_rawDescGZIP(), []int{4}
}

func (x *FindAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  []string `protobuf:"bytes,2,rep,name=error,proto3" json:"error,omitempty"`
	Data   *Account `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FindAccountResponse) Reset() {
	*x = FindAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccountResponse) ProtoMessage() {}

func (x *FindAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_bank_account_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccountResponse.ProtoReflect.Descriptor instead.
func (*FindAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_bank_account_query_proto_rawDescGZIP(), []int{5}
}

func (x *FindAccountResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FindAccountResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *FindAccountResponse) GetData() *Account {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_common_proto_bank_account_query_proto protoreflect.FileDescriptor

var file_pkg_common_proto_bank_account_query_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2d,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x62, 0x61, 0x6e,
	0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x4d, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x96,
	0x01, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37,
	0x0a, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x43, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x24, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x74, 0x0a, 0x13, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x32, 0xe9, 0x01, 0x0a, 0x17, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0b,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x2e, 0x62, 0x61,
	0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c,
	0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x12, 0x2a, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02,
	0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_common_proto_bank_account_query_proto_rawDescOnce sync.Once
	file_pkg_common_proto_bank_account_query_proto_rawDescData = file_pkg_common_proto_bank_account_query_proto_rawDesc
)

func file_pkg_common_proto_bank_account_query_proto_rawDescGZIP() []byte {
	file_pkg_common_proto_bank_account_query_proto_rawDescOnce.Do(func() {
		file_pkg_common_proto_bank_account_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_common_proto_bank_account_query_proto_rawDescData)
	})
	return file_pkg_common_proto_bank_account_query_proto_rawDescData
}

var file_pkg_common_proto_bank_account_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_common_proto_bank_account_query_proto_goTypes = []interface{}{
	(*Account)(nil),                     // 0: bank_account_query.Account
	(*FindAllAccountsResponseData)(nil), // 1: bank_account_query.FindAllAccountsResponseData
	(*FindAllAccountsRequest)(nil),      // 2: bank_account_query.FindAllAccountsRequest
	(*FindAllAccountsResponse)(nil),     // 3: bank_account_query.FindAllAccountsResponse
	(*FindAccountRequest)(nil),          // 4: bank_account_query.FindAccountRequest
	(*FindAccountResponse)(nil),         // 5: bank_account_query.FindAccountResponse
}
var file_pkg_common_proto_bank_account_query_proto_depIdxs = []int32{
	0, // 0: bank_account_query.FindAllAccountsResponseData.accounts:type_name -> bank_account_query.Account
	1, // 1: bank_account_query.FindAllAccountsResponse.data:type_name -> bank_account_query.FindAllAccountsResponseData
	0, // 2: bank_account_query.FindAccountResponse.data:type_name -> bank_account_query.Account
	4, // 3: bank_account_query.BankAccountQueryService.FindAccount:input_type -> bank_account_query.FindAccountRequest
	2, // 4: bank_account_query.BankAccountQueryService.FindAllAccounts:input_type -> bank_account_query.FindAllAccountsRequest
	5, // 5: bank_account_query.BankAccountQueryService.FindAccount:output_type -> bank_account_query.FindAccountResponse
	3, // 6: bank_account_query.BankAccountQueryService.FindAllAccounts:output_type -> bank_account_query.FindAllAccountsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_common_proto_bank_account_query_proto_init() }
func file_pkg_common_proto_bank_account_query_proto_init() {
	if File_pkg_common_proto_bank_account_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_common_proto_bank_account_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_common_proto_bank_account_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAccountsResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_common_proto_bank_account_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAccountsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_common_proto_bank_account_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAccountsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_common_proto_bank_account_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_common_proto_bank_account_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_common_proto_bank_account_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_common_proto_bank_account_query_proto_goTypes,
		DependencyIndexes: file_pkg_common_proto_bank_account_query_proto_depIdxs,
		MessageInfos:      file_pkg_common_proto_bank_account_query_proto_msgTypes,
	}.Build()
	File_pkg_common_proto_bank_account_query_proto = out.File
	file_pkg_common_proto_bank_account_query_proto_rawDesc = nil
	file_pkg_common_proto_bank_account_query_proto_goTypes = nil
	file_pkg_common_proto_bank_account_query_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BankAccountQueryServiceClient is the client API for BankAccountQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BankAccountQueryServiceClient interface {
	FindAccount(ctx context.Context, in *FindAccountRequest, opts ...grpc.CallOption) (*FindAccountResponse, error)
	FindAllAccounts(ctx context.Context, in *FindAllAccountsRequest, opts ...grpc.CallOption) (*FindAllAccountsResponse, error)
}

type bankAccountQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankAccountQueryServiceClient(cc grpc.ClientConnInterface) BankAccountQueryServiceClient {
	return &bankAccountQueryServiceClient{cc}
}

func (c *bankAccountQueryServiceClient) FindAccount(ctx context.Context, in *FindAccountRequest, opts ...grpc.CallOption) (*FindAccountResponse, error) {
	out := new(FindAccountResponse)
	err := c.cc.Invoke(ctx, "/bank_account_query.BankAccountQueryService/FindAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankAccountQueryServiceClient) FindAllAccounts(ctx context.Context, in *FindAllAccountsRequest, opts ...grpc.CallOption) (*FindAllAccountsResponse, error) {
	out := new(FindAllAccountsResponse)
	err := c.cc.Invoke(ctx, "/bank_account_query.BankAccountQueryService/FindAllAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankAccountQueryServiceServer is the server API for BankAccountQueryService service.
type BankAccountQueryServiceServer interface {
	FindAccount(context.Context, *FindAccountRequest) (*FindAccountResponse, error)
	FindAllAccounts(context.Context, *FindAllAccountsRequest) (*FindAllAccountsResponse, error)
}

// UnimplementedBankAccountQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBankAccountQueryServiceServer struct {
}

func (*UnimplementedBankAccountQueryServiceServer) FindAccount(context.Context, *FindAccountRequest) (*FindAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAccount not implemented")
}
func (*UnimplementedBankAccountQueryServiceServer) FindAllAccounts(context.Context, *FindAllAccountsRequest) (*FindAllAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllAccounts not implemented")
}

func RegisterBankAccountQueryServiceServer(s *grpc.Server, srv BankAccountQueryServiceServer) {
	s.RegisterService(&_BankAccountQueryService_serviceDesc, srv)
}

func _BankAccountQueryService_FindAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankAccountQueryServiceServer).FindAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank_account_query.BankAccountQueryService/FindAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankAccountQueryServiceServer).FindAccount(ctx, req.(*FindAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankAccountQueryService_FindAllAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankAccountQueryServiceServer).FindAllAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank_account_query.BankAccountQueryService/FindAllAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankAccountQueryServiceServer).FindAllAccounts(ctx, req.(*FindAllAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BankAccountQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bank_account_query.BankAccountQueryService",
	HandlerType: (*BankAccountQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAccount",
			Handler:    _BankAccountQueryService_FindAccount_Handler,
		},
		{
			MethodName: "FindAllAccounts",
			Handler:    _BankAccountQueryService_FindAllAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/common/proto/bank-account-query.proto",
}
